server:
  port: 8088
spring: 
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 60s
    jedis: 
      pool: 
        max-idle: -1
        min-idle: 50
        max-active: -1
        max-wait: -1s  